export const userConstant = {
    "USER_LOGOUT": "USER_LOGOUT",

    "USER_LOGIN_REQUEST": "USER_LOGIN_REQUEST",
    "USER_LOGIN_SUCCESS": "USER_LOGIN_SUCCESS",
    "USER_LOGIN_ERROR_VALIDATION": "USER_LOGIN_ERROR_VALIDATION",
    "USER_LOGIN_ERROR_MESSAGE": "USER_LOGIN_ERROR_MESSAGE",
    "USER_LOGIN_FAILURE": "USER_LOGIN_FAILURE",

    "USER_REGISTER_REQUEST": "USER_REGISTER_REQUEST",
    "USER_REGSITER_SUCCESS": "USER_REGSITER_SUCCESS",
    "USER_REGSITER_ERROR_VALIDATION": "USER_REGSITER_ERROR_VALIDATION",
    "USER_REGSITER_ERROR_MESSAGE": "USER_REGSITER_ERROR_MESSAGE",
    "USER_REGSITER_FAILURE": "USER_REGSITER_FAILURE",

    "USER_IS_LOGIN_REQUEST": "USER_IS_LOGIN_REQUEST",
    "USER_IS_LOGIN_SUCCESS": "USER_IS_LOGIN_SUCCESS",
    "USER_IS_LOGIN_FAILURE": "USER_IS_LOGIN_FAILURE", 
}


export const profileConstant = {
    "USER_PROFILE_REQUEST": "USER_PROFILE_REQUEST",
    "USER_PROFILE_SUCCESS": "USER_PROFILE_SUCCESS",
    "USER_PROFILE_FAILURE": "USER_PROFILE_FAILURE",

    "USER_UPDATE_PROFILE_REQUEST": "USER_UPDATE_PROFILE_REQUEST",
    "USER_UPDATE_PROFILE_SUCCESS": "USER_UPDATE_PROFILE_SUCCESS",
    "USER_UPDATE_PROFILE_FAILURE": "USER_UPDATE_PROFILE_FAILURE",
    
    "RESET_PROFILE": "RESET_PROFILE"
}

export const postConstant = {
    "USER_CREATE_POST_REQUEST": "USER_CREATE_POST_REQUEST",
    "USER_CREATE_POST_SUCCESS": "USER_CREATE_POST_SUCCESS",
    "USER_CREATE_POST_VALIDATION": "USER_CREATE_POST_VALIDATION",
    "USER_CREATE_POST_FAILURE": "USER_CREATE_POST_FAILURE",
    "USER_POST_CLEAR_MESSAGE": "USER_POST_CLEAR_MESSAGE",

    "GET_USER_BY_ID_REQUEST": "GET_USER_BY_ID_REQUEST",
    "GET_USER_BY_ID_SUCCESS": "GET_USER_BY_ID_SUCCESS",
    "GET_USER_BY_ID_FAILURE": "GET_USER_BY_ID_FAILURE",
}