export const userConstant = {
    "USER_LOGOUT": "USER_LOGOUT",

    "USER_LOGIN_REQUEST": "USER_LOGIN_REQUEST",
    "USER_LOGIN_SUCCESS": "USER_LOGIN_SUCCESS",
    "USER_LOGIN_ERROR_VALIDATION": "USER_LOGIN_ERROR_VALIDATION",
    "USER_LOGIN_ERROR_MESSAGE": "USER_LOGIN_ERROR_MESSAGE",
    "USER_LOGIN_FAILURE": "USER_LOGIN_FAILURE",

    "USER_REGISTER_REQUEST": "USER_REGISTER_REQUEST",
    "USER_REGSITER_SUCCESS": "USER_REGSITER_SUCCESS",
    "USER_REGSITER_ERROR_VALIDATION": "USER_REGSITER_ERROR_VALIDATION",
    "USER_REGSITER_ERROR_MESSAGE": "USER_REGSITER_ERROR_MESSAGE",
    "USER_REGSITER_FAILURE": "USER_REGSITER_FAILURE",

    "USER_IS_LOGIN_REQUEST": "USER_IS_LOGIN_REQUEST",
    "USER_IS_LOGIN_SUCCESS": "USER_IS_LOGIN_SUCCESS",
    "USER_IS_LOGIN_FAILURE": "USER_IS_LOGIN_FAILURE",
}